INSERT INTO country (a2_code, `name`, memo) VALUE
  ('AD','Andorra',NULL),
  ('AE','United Arab Emirates',NULL),
  ('AF','Afghanistan',NULL),
  ('AG','Antigua and Barbuda',NULL),
  ('AI','Anguilla','AI previously represented French Afar and Issas'),
  ('AL','Albania',NULL),
  ('AM','Armenia',NULL),
  ('AO','Angola',NULL),
  ('AQ','Antarctica','Covers the territories south of 60° south latitude. \nCode taken from name in French: Antarctique'),
  ('AR','Argentina',NULL),
  ('AS','American Samoa',NULL),
  ('AT','Austria',NULL),
  ('AU','Australia','Includes the Ashmore and Cartier Islands and the Coral Sea Islands'),
  ('AW','Aruba',NULL),
  ('AX','Åland Islands','An autonomous province of Finland'),
  ('AZ','Azerbaijan',NULL),
  ('BA','Bosnia and Herzegovina',NULL),
  ('BB','Barbados',NULL),
  ('BD','Bangladesh',NULL),
  ('BE','Belgium',NULL),
  ('BF','Burkina Faso','Name changed from Upper Volta (HV)'),
  ('BG','Bulgaria',NULL),
  ('BH','Bahrain',NULL),
  ('BI','Burundi',NULL),
  ('BJ','Benin','Name changed from Dahomey (DY)'),
  ('BL','Saint Barthélemy',NULL),
  ('BM','Bermuda',NULL),
  ('BN','Brunei Darussalam','ISO country name follows UN designation (common name: Brunei)'),
  ('BO','Bolivia, Plurinational State of','ISO country name follows UN designation (common name and previous ISO country name: Bolivia)'),
  ('BQ','Bonaire, Sint Eustatius and Saba','Consists of three Caribbean \"special municipalities\", which are part of the Netherlands proper: Bonaire, Sint Eustatius, and Saba (the BES Islands). \nPrevious ISO country name: Bonaire, Saint Eustatius and Saba. \nBQ previously represented British Antarctic Territory'),
  ('BR','Brazil',NULL),
  ('BS','Bahamas',NULL),
  ('BT','Bhutan',NULL),
  ('BV','Bouvet Island','Belongs to Norway'),
  ('BW','Botswana',NULL),
  ('BY','Belarus','"Code taken from previous ISO country name: Byelorussian SSR (now assigned ISO 3166-3 code BYAA). \nCode assigned as the country was already a UN member since 1945"'),
  ('BZ','Belize',NULL),
  ('CA','Canada',NULL),
  ('CC','Cocos (Keeling) Islands',NULL),
  ('CD','Congo, the Democratic Republic of the','Name changed from Zaire (ZR)'),
  ('CF','Central African Republic',NULL),
  ('CG','Congo',NULL),
  ('CH','Switzerland','Code taken from name in Latin: Confoederatio Helvetica'),
  ('CI','Côte d\'Ivoire',NULL),
  ('CK','Cook Islands',NULL),
  ('CL','Chile',NULL),
  ('CM','Cameroon',NULL),
  ('CN','China',NULL),
  ('CO','Colombia',NULL),
  ('CR','Costa Rica',NULL),
  ('CU','Cuba',NULL),
  ('CV','Cabo Verde',NULL),
  ('CW','Curaçao',NULL),
  ('CX','Christmas Island',NULL),
  ('CY','Cyprus',NULL),
  ('CZ','Czech Republic',NULL),
  ('DE','Germany','"Code taken from name in German: Deutschland. \nCode used for West Germany before 1990 (previous ISO country name: Germany, Federal Republic of)"'),
  ('DJ','Djibouti','Name changed from French Afar and Issas (AI)'),
  ('DK','Denmark',NULL),
  ('DM','Dominica',NULL),
  ('DO','Dominican Republic',NULL),
  ('DZ','Algeria','Code taken from name in Kabyle: Dzayer'),
  ('EC','Ecuador',NULL),
  ('EE','Estonia','Code taken from name in Estonian: Eesti'),
  ('EG','Egypt',NULL),
  ('EH','Western Sahara','Previous ISO country name: Spanish Sahara (code taken from name in Spanish: Sahara español)'),
  ('ER','Eritrea',NULL),
  ('ES','Spain','Code taken from name in Spanish: España'),
  ('ET','Ethiopia',NULL),
  ('FI','Finland',NULL),
  ('FJ','Fiji',NULL),
  ('FK','Falkland Islands (Malvinas)',NULL),
  ('FM','Micronesia, Federated States of','Previous ISO country name: Micronesia'),
  ('FO','Faroe Islands',NULL),
  ('FR','France','Includes Clipperton Island'),
  ('GA','Gabon',NULL),
  ('GB','United Kingdom of Great Britain and Northern Ireland','"Code taken from Great Britain (from official name: United Kingdom of Great Britain and Northern Ireland). \n.uk is the primary ccTLD of the United Kingdom instead of .gb (see code UK, which is exceptionally reserved)"'),
  ('GD','Grenada',NULL),
  ('GE','Georgia','GE previously represented Gilbert and Ellice Islands'),
  ('GF','French Guiana','Code taken from name in French: Guyane française'),
  ('GG','Guernsey','a British Crown dependency'),
  ('GH','Ghana',NULL),
  ('GI','Gibraltar',NULL),
  ('GL','Greenland',NULL),
  ('GM','Gambia',NULL),
  ('GN','Guinea',NULL),
  ('GP','Guadeloupe',NULL),
  ('GQ','Equatorial Guinea','Code taken from name in French: Guinée équatoriale'),
  ('GR','Greece',NULL),
  ('GS','South Georgia and the South Sandwich Islands',NULL),
  ('GT','Guatemala',NULL),
  ('GU','Guam',NULL),
  ('GW','Guinea-Bissau',NULL),
  ('GY','Guyana',NULL),
  ('HK','Hong Kong',NULL),
  ('HM','Heard Island and McDonald Islands',NULL),
  ('HN','Honduras',NULL),
  ('HR','Croatia','Code taken from name in Croatian: Hrvatska'),
  ('HT','Haiti',NULL),
  ('HU','Hungary',NULL),
  ('ID','Indonesia',NULL),
  ('IE','Ireland',NULL),
  ('IL','Israel',NULL),
  ('IM','Isle of Man','a British Crown dependency'),
  ('IN','India',NULL),
  ('IO','British Indian Ocean Territory',NULL),
  ('IQ','Iraq',NULL),
  ('IR','Iran, Islamic Republic of','ISO country name follows UN designation (common name: Iran)'),
  ('IS','Iceland','Code taken from name in Icelandic: Ísland'),
  ('IT','Italy',NULL),
  ('JE','Jersey','a British Crown dependency'),
  ('JM','Jamaica',NULL),
  ('JO','Jordan',NULL),
  ('JP','Japan',NULL),
  ('KE','Kenya',NULL),
  ('KG','Kyrgyzstan',NULL),
  ('KH','Cambodia','"Code taken from former name: Khmer Republic. \nPrevious ISO country name: Kampuchea"'),
  ('KI','Kiribati',NULL),
  ('KM','Comoros','Code taken from name in Comorian: Komori'),
  ('KN','Saint Kitts and Nevis','Previous ISO country name: Saint Kitts-Nevis-Anguilla'),
  ('KP','Korea, Democratic People\'s Republic of','ISO country name follows UN designation (common name: North Korea)'),
  ('KR','Korea, Republic of','ISO country name follows UN designation (common name: South Korea)'),
  ('KW','Kuwait',NULL),
  ('KY','Cayman Islands',NULL),
  ('KZ','Kazakhstan','Previous ISO country name: Kazakstan'),
  ('LA','Lao People\'s Democratic Republic','ISO country name follows UN designation (common name: Laos)'),
  ('LB','Lebanon',NULL),
  ('LC','Saint Lucia',NULL),
  ('LI','Liechtenstein',NULL),
  ('LK','Sri Lanka',NULL),
  ('LR','Liberia',NULL),
  ('LS','Lesotho',NULL),
  ('LT','Lithuania',NULL),
  ('LU','Luxembourg',NULL),
  ('LV','Latvia',NULL),
  ('LY','Libya','Previous ISO country name: Libyan Arab Jamahiriya'),
  ('MA','Morocco','Code taken from name in French: Maroc'),
  ('MC','Monaco',NULL),
  ('MD','Moldova, Republic of','ISO country name follows UN designation (common name and previous ISO country name: Moldova)'),
  ('ME','Montenegro',NULL),
  ('MF','Saint Martin (French part)','The Dutch part of Saint Martin island is assigned code SX'),
  ('MG','Madagascar',NULL),
  ('MH','Marshall Islands',NULL),
  ('MK','Macedonia, the former Yugoslav Republic of','"ISO country name follows UN designation (due to Macedonia naming dispute; official name used by country itself: Republic of Macedonia). \nCode taken from name in Macedonian: Makedonija"'),
  ('ML','Mali',NULL),
  ('MM','Myanmar','Name changed from Burma (BU)'),
  ('MN','Mongolia',NULL),
  ('MO','Macao','Previous ISO country name: Macau'),
  ('MP','Northern Mariana Islands',NULL),
  ('MQ','Martinique',NULL),
  ('MR','Mauritania',NULL),
  ('MS','Montserrat',NULL),
  ('MT','Malta',NULL),
  ('MU','Mauritius',NULL),
  ('MV','Maldives',NULL),
  ('MW','Malawi',NULL),
  ('MX','Mexico',NULL),
  ('MY','Malaysia',NULL),
  ('MZ','Mozambique',NULL),
  ('NA','Namibia',NULL),
  ('NC','New Caledonia',NULL),
  ('NE','Niger',NULL),
  ('NF','Norfolk Island',NULL),
  ('NG','Nigeria',NULL),
  ('NI','Nicaragua',NULL),
  ('NL','Netherlands',NULL),
  ('NO','Norway',NULL),
  ('NP','Nepal',NULL),
  ('NR','Nauru',NULL),
  ('NU','Niue',NULL),
  ('NZ','New Zealand',NULL),
  ('OM','Oman',NULL),
  ('PA','Panama',NULL),
  ('PE','Peru',NULL),
  ('PF','French Polynesia','Code taken from name in French: Polynésie française'),
  ('PG','Papua New Guinea',NULL),
  ('PH','Philippines',NULL),
  ('PK','Pakistan',NULL),
  ('PL','Poland',NULL),
  ('PM','Saint Pierre and Miquelon',NULL),
  ('PN','Pitcairn',NULL),
  ('PR','Puerto Rico',NULL),
  ('PS','Palestine, State of','"Previous ISO country name: Palestinian Territory, Occupied. \nConsists of the West Bank and the Gaza Strip"'),
  ('PT','Portugal',NULL),
  ('PW','Palau',NULL),
  ('PY','Paraguay',NULL),
  ('QA','Qatar',NULL),
  ('RE','Réunion',NULL),
  ('RO','Romania',NULL),
  ('RS','Serbia','Code taken from official name: Republic of Serbia (see Serbian country codes)'),
  ('RU','Russian Federation','ISO country name follows UN designation (common name: Russia)'),
  ('RW','Rwanda',NULL),
  ('SA','Saudi Arabia',NULL),
  ('SB','Solomon Islands','Code taken from former name: British Solomon Islands'),
  ('SC','Seychelles',NULL),
  ('SD','Sudan',NULL),
  ('SE','Sweden',NULL),
  ('SG','Singapore',NULL),
  ('SH','Saint Helena, Ascension and Tristan da Cunha','Previous ISO country name: Saint Helena'),
  ('SI','Slovenia',NULL),
  ('SJ','Svalbard and Jan Mayen','Consists of two arctic territories of Norway: Svalbard and Jan Mayen'),
  ('SK','Slovakia','SK previously represented Sikkim'),
  ('SL','Sierra Leone',NULL),
  ('SM','San Marino',NULL),
  ('SN','Senegal',NULL),
  ('SO','Somalia',NULL),
  ('SR','Suriname',NULL),
  ('SS','South Sudan',NULL),
  ('ST','Sao Tome and Principe',NULL),
  ('SV','El Salvador',NULL),
  ('SX','Sint Maarten (Dutch part)','The French part of Saint Martin island is assigned code MF'),
  ('SY','Syrian Arab Republic','ISO country name follows UN designation (common name: Syria)'),
  ('SZ','Swaziland',NULL),
  ('TC','Turks and Caicos Islands',NULL),
  ('TD','Chad','Code taken from name in French: Tchad'),
  ('TF','French Southern Territories','"Covers the French Southern and Antarctic Lands except Adélie Land. \nCode taken from name in French: Terres australes françaises"'),
  ('TG','Togo',NULL),
  ('TH','Thailand',NULL),
  ('TJ','Tajikistan',NULL),
  ('TK','Tokelau',NULL),
  ('TL','Timor-Leste','Name changed from East Timor (TP)'),
  ('TM','Turkmenistan',NULL),
  ('TN','Tunisia',NULL),
  ('TO','Tonga',NULL),
  ('TR','Turkey',NULL),
  ('TT','Trinidad and Tobago',NULL),
  ('TV','Tuvalu',NULL),
  ('TW','Taiwan, Province of China','"Covers the current jurisdiction of the Republic of China except Kinmen and Lienchiang. \nISO country name follows UN designation (due to political status of Taiwan within the UN)"'),
  ('TZ','Tanzania, United Republic of','ISO country name follows UN designation (common name: Tanzania)'),
  ('UA','Ukraine','"Previous ISO country name: Ukrainian SSR. \nCode assigned as the country was already a UN member since 1945"'),
  ('UG','Uganda',NULL),
  ('UM','United States Minor Outlying Islands','Consists of nine minor insular areas of the United States: Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Islands, Navassa Island, Palmyra Atoll, and Wake Island'),
  ('US','United States of America',NULL),
  ('UY','Uruguay',NULL),
  ('UZ','Uzbekistan',NULL),
  ('VA','Holy See','"Covers Vatican City, territory of the Holy See. \nPrevious ISO country name: Vatican City State (Holy See)"'),
  ('VC','Saint Vincent and the Grenadines',NULL),
  ('VE','Venezuela, Bolivarian Republic of','ISO country name follows UN designation (common name and previous ISO country name: Venezuela)'),
  ('VG','Virgin Islands, British',NULL),
  ('VI','Virgin Islands, U.S.',NULL),
  ('VN','Viet Nam','ISO country name follows UN designation (common name: Vietnam)'),
  ('VU','Vanuatu','Name changed from New Hebrides (NH)'),
  ('WF','Wallis and Futuna',NULL),
  ('WS','Samoa','Code taken from former name: Western Samoa'),
  ('YE','Yemen','"Previous ISO country name: Yemen, Republic of. \nCode used for North Yemen before 1990"'),
  ('YT','Mayotte',NULL),
  ('ZA','South Africa','Code taken from name in Dutch: Zuid-Afrika'),
  ('ZM','Zambia',NULL),
  ('ZW','Zimbabwe','Name changed from Southern Rhodesia (RH)')
;