USE `sseip`;
INSERT INTO `country` (`name`, `memo`, `updated`, `a2_code`, `name_en`) VALUES
  ('安道尔', NULL, now(), 'AD', 'Andorra'),
  ('阿联酋', NULL, now(), 'AE', 'United Arab Emirates'),
  ('阿富汗', NULL, now(), 'AF', 'Afghanistan'),
  ('安提瓜和巴布达', NULL, now(), 'AG', 'Antigua and Barbuda'),
  ('安圭拉', 'AI previously represented French Afar and Issas', now(), 'AI', 'Anguilla'),
  ('阿尔巴尼亚', NULL, now(), 'AL', 'Albania'),
  ('亚美尼亚', NULL, now(), 'AM', 'Armenia'),
  ('安哥拉', NULL, now(), 'AO', 'Angola'),
  ('南极洲', 'Covers the territories south of 60° south latitude. \nCode taken from name in French: Antarctique', now(), 'AQ', 'Antarctica'),
  ('阿根廷', NULL, now(), 'AR', 'Argentina'),
  ('美属萨摩亚', NULL, now(), 'AS', 'American Samoa'),
  ('奥地利', NULL, now(), 'AT', 'Austria'),
  ('澳大利亚', 'Includes the Ashmore and Cartier Islands and the Coral Sea Islands', now(), 'AU', 'Australia'),
  ('阿鲁巴', NULL, now(), 'AW', 'Aruba'),
  ('奥兰', 'An autonomous province of Finland', now(), 'AX', 'Åland Islands'),
  ('阿塞拜疆', NULL, now(), 'AZ', 'Azerbaijan'),
  ('波斯尼亚和黑塞哥维那', NULL, now(), 'BA', 'Bosnia and Herzegovina'),
  ('巴巴多斯', NULL, now(), 'BB', 'Barbados'),
  ('孟加拉国', NULL, now(), 'BD', 'Bangladesh'),
  ('比利时', NULL, now(), 'BE', 'Belgium'),
  ('布基纳法索', 'Name changed from Upper Volta (HV)', now(), 'BF', 'Burkina Faso'),
  ('保加利亚', NULL, now(), 'BG', 'Bulgaria'),
  ('巴林', NULL, now(), 'BH', 'Bahrain'),
  ('布隆迪', NULL, now(), 'BI', 'Burundi'),
  ('贝宁', 'Name changed from Dahomey (DY)', now(), 'BJ', 'Benin'),
  ('圣巴泰勒米', NULL, now(), 'BL', 'Saint Barthélemy'),
  ('百慕大', NULL, now(), 'BM', 'Bermuda'),
  ('文莱', 'ISO country name follows UN designation (common name: Brunei)', now(), 'BN', 'Brunei Darussalam'),
  ('玻利维亚', 'ISO country name follows UN designation (common name and previous ISO country name: Bolivia)', now(), 'BO', 'Bolivia, Plurinational State of'),
  ('加勒比荷兰', 'Consists of three Caribbean \"special municipalities\", which are part of the Netherlands proper: Bonaire, Sint Eustatius, and Saba (the BES Islands). \nPrevious ISO country name: Bonaire, Saint Eustatius and Saba. \nBQ previously represented British Antarctic Territory', now(), 'BQ', 'Bonaire, Sint Eustatius and Saba'),
  ('巴西', NULL, now(), 'BR', 'Brazil'),
  ('巴哈马', NULL, now(), 'BS', 'Bahamas'),
  ('不丹', NULL, now(), 'BT', 'Bhutan'),
  ('布韦岛', 'Belongs to Norway', now(), 'BV', 'Bouvet Island'),
  ('博茨瓦纳', NULL, now(), 'BW', 'Botswana'),
  ('白俄罗斯', '\"Code taken from previous ISO country name: Byelorussian SSR (now assigned ISO 3166-3 code BYAA). \nCode assigned as the country was already a UN member since 1945\"', now(), 'BY', 'Belarus'),
  ('伯利兹', NULL, now(), 'BZ', 'Belize'),
  ('加拿大', NULL, now(), 'CA', 'Canada'),
  ('科科斯（基林）群岛', NULL, now(), 'CC', 'Cocos (Keeling) Islands'),
  ('民主刚果', 'Name changed from Zaire (ZR)', now(), 'CD', 'Congo, the Democratic Republic of the'),
  ('中非共和国', NULL, now(), 'CF', 'Central African Republic'),
  ('刚果', NULL, now(), 'CG', 'Congo'),
  ('瑞士', 'Code taken from name in Latin: Confoederatio Helvetica', now(), 'CH', 'Switzerland'),
  ('科特迪瓦', NULL, now(), 'CI', 'Côte d\'Ivoire'),
  ('库克群岛', NULL, now(), 'CK', 'Cook Islands'),
  ('智利', NULL, now(), 'CL', 'Chile'),
  ('喀麦隆', NULL, now(), 'CM', 'Cameroon'),
  ('中国', NULL, now(), 'CN', 'China'),
  ('哥伦比亚', NULL, now(), 'CO', 'Colombia'),
  ('哥斯达黎加', NULL, now(), 'CR', 'Costa Rica'),
  ('古巴', NULL, now(), 'CU', 'Cuba'),
  ('佛得角', NULL, now(), 'CV', 'Cabo Verde'),
  ('库拉索', NULL, now(), 'CW', 'Curaçao'),
  ('圣诞岛', NULL, now(), 'CX', 'Christmas Island'),
  ('塞浦路斯', NULL, now(), 'CY', 'Cyprus'),
  ('捷克', NULL, now(), 'CZ', 'Czech Republic'),
  ('德国', '\"Code taken from name in German: Deutschland. \nCode used for West Germany before 1990 (previous ISO country name: Germany, Federal Republic of)\"', now(), 'DE', 'Germany'),
  ('吉布提', 'Name changed from French Afar and Issas (AI)', now(), 'DJ', 'Djibouti'),
  ('丹麦', NULL, now(), 'DK', 'Denmark'),
  ('多米尼克', NULL, now(), 'DM', 'Dominica'),
  ('多米尼加', NULL, now(), 'DO', 'Dominican Republic'),
  ('阿尔及利亚', 'Code taken from name in Kabyle: Dzayer', now(), 'DZ', 'Algeria'),
  ('厄瓜多尔', NULL, now(), 'EC', 'Ecuador'),
  ('爱沙尼亚', 'Code taken from name in Estonian: Eesti', now(), 'EE', 'Estonia'),
  ('埃及', NULL, now(), 'EG', 'Egypt'),
  ('撒拉威阿拉伯民主共和国', 'Previous ISO country name: Spanish Sahara (code taken from name in Spanish: Sahara español)', now(), 'EH', 'Western Sahara'),
  ('厄立特里亚', NULL, now(), 'ER', 'Eritrea'),
  ('西班牙', 'Code taken from name in Spanish: España', now(), 'ES', 'Spain'),
  ('埃塞俄比亚', NULL, now(), 'ET', 'Ethiopia'),
  ('芬兰', NULL, now(), 'FI', 'Finland'),
  ('斐济', NULL, now(), 'FJ', 'Fiji'),
  ('福克兰群岛', NULL, now(), 'FK', 'Falkland Islands (Malvinas)'),
  ('密克罗尼西亚联邦', 'Previous ISO country name: Micronesia', now(), 'FM', 'Micronesia, Federated States of'),
  ('法罗群岛', NULL, now(), 'FO', 'Faroe Islands'),
  ('法国', 'Includes Clipperton Island', now(), 'FR', 'France'),
  ('加蓬', NULL, now(), 'GA', 'Gabon'),
  ('英国', '\"Code taken from Great Britain (from official name: United Kingdom of Great Britain and Northern Ireland). \n.uk is the primary ccTLD of the United Kingdom instead of .gb (see code UK, which is exceptionally reserved)\"', now(), 'GB', 'United Kingdom of Great Britain and Northern Ireland'),
  ('格林纳达', NULL, now(), 'GD', 'Grenada'),
  ('格鲁吉亚', 'GE previously represented Gilbert and Ellice Islands', now(), 'GE', 'Georgia'),
  ('法属圭亚那', 'Code taken from name in French: Guyane française', now(), 'GF', 'French Guiana'),
  ('根西', 'a British Crown dependency', now(), 'GG', 'Guernsey'),
  ('加纳', NULL, now(), 'GH', 'Ghana'),
  ('直布罗陀', NULL, now(), 'GI', 'Gibraltar'),
  ('格陵兰', NULL, now(), 'GL', 'Greenland'),
  ('冈比亚', NULL, now(), 'GM', 'Gambia'),
  ('几内亚', NULL, now(), 'GN', 'Guinea'),
  ('瓜德罗普', NULL, now(), 'GP', 'Guadeloupe'),
  ('赤道几内亚', 'Code taken from name in French: Guinée équatoriale', now(), 'GQ', 'Equatorial Guinea'),
  ('希腊', NULL, now(), 'GR', 'Greece'),
  ('南乔治亚和南桑威奇群岛', NULL, now(), 'GS', 'South Georgia and the South Sandwich Islands'),
  ('危地马拉', NULL, now(), 'GT', 'Guatemala'),
  ('关岛', NULL, now(), 'GU', 'Guam'),
  ('几内亚比绍', NULL, now(), 'GW', 'Guinea-Bissau'),
  ('圭亚那', NULL, now(), 'GY', 'Guyana'),
  ('中国香港', NULL, now(), 'HK', 'Hong Kong'),
  ('赫德岛和麦克唐纳群岛', NULL, now(), 'HM', 'Heard Island and McDonald Islands'),
  ('洪都拉斯', NULL, now(), 'HN', 'Honduras'),
  ('克罗地亚', 'Code taken from name in Croatian: Hrvatska', now(), 'HR', 'Croatia'),
  ('海地', NULL, now(), 'HT', 'Haiti'),
  ('匈牙利', NULL, now(), 'HU', 'Hungary'),
  ('印度尼西亚', NULL, now(), 'ID', 'Indonesia'),
  ('爱尔兰', NULL, now(), 'IE', 'Ireland'),
  ('以色列', NULL, now(), 'IL', 'Israel'),
  ('马恩岛', 'a British Crown dependency', now(), 'IM', 'Isle of Man'),
  ('印度', NULL, now(), 'IN', 'India'),
  ('英属印度洋领地', NULL, now(), 'IO', 'British Indian Ocean Territory'),
  ('伊拉克', NULL, now(), 'IQ', 'Iraq'),
  ('伊朗', 'ISO country name follows UN designation (common name: Iran)', now(), 'IR', 'Iran, Islamic Republic of'),
  ('冰岛', 'Code taken from name in Icelandic: Ísland', now(), 'IS', 'Iceland'),
  ('意大利', NULL, now(), 'IT', 'Italy'),
  ('泽西', 'a British Crown dependency', now(), 'JE', 'Jersey'),
  ('牙买加', NULL, now(), 'JM', 'Jamaica'),
  ('约旦', NULL, now(), 'JO', 'Jordan'),
  ('日本', NULL, now(), 'JP', 'Japan'),
  ('肯尼亚', NULL, now(), 'KE', 'Kenya'),
  ('吉尔吉斯斯坦', NULL, now(), 'KG', 'Kyrgyzstan'),
  ('柬埔寨', '\"Code taken from former name: Khmer Republic. \nPrevious ISO country name: Kampuchea\"', now(), 'KH', 'Cambodia'),
  ('基里巴斯', NULL, now(), 'KI', 'Kiribati'),
  ('科摩罗', 'Code taken from name in Comorian: Komori', now(), 'KM', 'Comoros'),
  ('圣基茨和尼维斯', 'Previous ISO country name: Saint Kitts-Nevis-Anguilla', now(), 'KN', 'Saint Kitts and Nevis'),
  ('朝鲜', 'ISO country name follows UN designation (common name: North Korea)', now(), 'KP', 'Korea, Democratic People\'s Republic of'),
  ('韩国', 'ISO country name follows UN designation (common name: South Korea)', now(), 'KR', 'Korea, Republic of'),
  ('科威特', NULL, now(), 'KW', 'Kuwait'),
  ('开曼群岛', NULL, now(), 'KY', 'Cayman Islands'),
  ('哈萨克斯坦', 'Previous ISO country name: Kazakstan', now(), 'KZ', 'Kazakhstan'),
  ('老挝', 'ISO country name follows UN designation (common name: Laos)', now(), 'LA', 'Lao People\'s Democratic Republic'),
  ('黎巴嫩', NULL, now(), 'LB', 'Lebanon'),
  ('圣卢西亚', NULL, now(), 'LC', 'Saint Lucia'),
  ('列支敦士登', NULL, now(), 'LI', 'Liechtenstein'),
  ('斯里兰卡', NULL, now(), 'LK', 'Sri Lanka'),
  ('利比里亚', NULL, now(), 'LR', 'Liberia'),
  ('莱索托', NULL, now(), 'LS', 'Lesotho'),
  ('立陶宛', NULL, now(), 'LT', 'Lithuania'),
  ('卢森堡', NULL, now(), 'LU', 'Luxembourg'),
  ('拉脱维亚', NULL, now(), 'LV', 'Latvia'),
  ('利比亚', 'Previous ISO country name: Libyan Arab Jamahiriya', now(), 'LY', 'Libya'),
  ('摩洛哥', 'Code taken from name in French: Maroc', now(), 'MA', 'Morocco'),
  ('摩纳哥', NULL, now(), 'MC', 'Monaco'),
  ('摩尔多瓦', 'ISO country name follows UN designation (common name and previous ISO country name: Moldova)', now(), 'MD', 'Moldova, Republic of'),
  ('黑山', NULL, now(), 'ME', 'Montenegro'),
  ('圣马丁行政区', 'The Dutch part of Saint Martin island is assigned code SX', now(), 'MF', 'Saint Martin (French part)'),
  ('马达加斯加', NULL, now(), 'MG', 'Madagascar'),
  ('马绍尔群岛', NULL, now(), 'MH', 'Marshall Islands'),
  ('马其顿共和国 马其顿', '\"ISO country name follows UN designation (due to Macedonia naming dispute; official name used by country itself: Republic of Macedonia). \nCode taken from name in Macedonian: Makedonija\"', now(), 'MK', 'Macedonia, the former Yugoslav Republic of'),
  ('马里', NULL, now(), 'ML', 'Mali'),
  ('缅甸', 'Name changed from Burma (BU)', now(), 'MM', 'Myanmar'),
  ('蒙古国', NULL, now(), 'MN', 'Mongolia'),
  ('中国澳门', 'Previous ISO country name: Macau', now(), 'MO', 'Macao'),
  ('北马里亚纳群岛', NULL, now(), 'MP', 'Northern Mariana Islands'),
  ('马提尼克', NULL, now(), 'MQ', 'Martinique'),
  ('毛里塔尼亚', NULL, now(), 'MR', 'Mauritania'),
  ('蒙特塞拉特', NULL, now(), 'MS', 'Montserrat'),
  ('马耳他', NULL, now(), 'MT', 'Malta'),
  ('毛里求斯', NULL, now(), 'MU', 'Mauritius'),
  ('马尔代夫', NULL, now(), 'MV', 'Maldives'),
  ('马拉维', NULL, now(), 'MW', 'Malawi'),
  ('墨西哥', NULL, now(), 'MX', 'Mexico'),
  ('马来西亚', NULL, now(), 'MY', 'Malaysia'),
  ('莫桑比克', NULL, now(), 'MZ', 'Mozambique'),
  ('纳米比亚', NULL, now(), 'NA', 'Namibia'),
  ('新喀里多尼亚', NULL, now(), 'NC', 'New Caledonia'),
  ('尼日尔', NULL, now(), 'NE', 'Niger'),
  ('诺福克岛', NULL, now(), 'NF', 'Norfolk Island'),
  ('尼日利亚', NULL, now(), 'NG', 'Nigeria'),
  ('尼加拉瓜', NULL, now(), 'NI', 'Nicaragua'),
  ('荷兰', NULL, now(), 'NL', 'Netherlands'),
  ('挪威', NULL, now(), 'NO', 'Norway'),
  ('尼泊尔', NULL, now(), 'NP', 'Nepal'),
  ('瑙鲁', NULL, now(), 'NR', 'Nauru'),
  ('纽埃', NULL, now(), 'NU', 'Niue'),
  ('新西兰', NULL, now(), 'NZ', 'New Zealand'),
  ('阿曼', NULL, now(), 'OM', 'Oman'),
  ('巴拿马', NULL, now(), 'PA', 'Panama'),
  ('秘鲁', NULL, now(), 'PE', 'Peru'),
  ('法属波利尼西亚', 'Code taken from name in French: Polynésie française', now(), 'PF', 'French Polynesia'),
  ('巴布亚新几内亚', NULL, now(), 'PG', 'Papua New Guinea'),
  ('菲律宾', NULL, now(), 'PH', 'Philippines'),
  ('巴基斯坦', NULL, now(), 'PK', 'Pakistan'),
  ('波兰', NULL, now(), 'PL', 'Poland'),
  ('圣皮埃尔和密克隆', NULL, now(), 'PM', 'Saint Pierre and Miquelon'),
  ('皮特凯恩群岛', NULL, now(), 'PN', 'Pitcairn'),
  ('波多黎各', NULL, now(), 'PR', 'Puerto Rico'),
  ('巴勒斯坦', '\"Previous ISO country name: Palestinian Territory, Occupied. \nConsists of the West Bank and the Gaza Strip\"', now(), 'PS', 'Palestine, State of'),
  ('葡萄牙', NULL, now(), 'PT', 'Portugal'),
  ('帕劳', NULL, now(), 'PW', 'Palau'),
  ('巴拉圭', NULL, now(), 'PY', 'Paraguay'),
  ('卡塔尔', NULL, now(), 'QA', 'Qatar'),
  ('留尼汪', NULL, now(), 'RE', 'Réunion'),
  ('罗马尼亚', NULL, now(), 'RO', 'Romania'),
  ('塞尔维亚', 'Code taken from official name: Republic of Serbia (see Serbian country codes)', now(), 'RS', 'Serbia'),
  ('俄罗斯', 'ISO country name follows UN designation (common name: Russia)', now(), 'RU', 'Russian Federation'),
  ('卢旺达', NULL, now(), 'RW', 'Rwanda'),
  ('沙特阿拉伯', NULL, now(), 'SA', 'Saudi Arabia'),
  ('所罗门群岛', 'Code taken from former name: British Solomon Islands', now(), 'SB', 'Solomon Islands'),
  ('塞舌尔', NULL, now(), 'SC', 'Seychelles'),
  ('苏丹', NULL, now(), 'SD', 'Sudan'),
  ('瑞典', NULL, now(), 'SE', 'Sweden'),
  ('新加坡', NULL, now(), 'SG', 'Singapore'),
  ('圣赫勒拿', 'Previous ISO country name: Saint Helena', now(), 'SH', 'Saint Helena, Ascension and Tristan da Cunha'),
  ('斯洛文尼亚', NULL, now(), 'SI', 'Slovenia'),
  ('挪威 斯瓦尔巴群岛和扬马延岛', 'Consists of two arctic territories of Norway: Svalbard and Jan Mayen', now(), 'SJ', 'Svalbard and Jan Mayen'),
  ('斯洛伐克', 'SK previously represented Sikkim', now(), 'SK', 'Slovakia'),
  ('塞拉利昂', NULL, now(), 'SL', 'Sierra Leone'),
  ('圣马力诺', NULL, now(), 'SM', 'San Marino'),
  ('塞内加尔', NULL, now(), 'SN', 'Senegal'),
  ('索马里', NULL, now(), 'SO', 'Somalia'),
  ('苏里南', NULL, now(), 'SR', 'Suriname'),
  ('南苏丹', NULL, now(), 'SS', 'South Sudan'),
  ('圣多美和普林西比', NULL, now(), 'ST', 'Sao Tome and Principe'),
  ('萨尔瓦多', NULL, now(), 'SV', 'El Salvador'),
  ('荷属圣马丁', 'The French part of Saint Martin island is assigned code MF', now(), 'SX', 'Sint Maarten (Dutch part)'),
  ('叙利亚', 'ISO country name follows UN designation (common name: Syria)', now(), 'SY', 'Syrian Arab Republic'),
  ('斯威士兰', NULL, now(), 'SZ', 'Swaziland'),
  ('特克斯和凯科斯群岛', NULL, now(), 'TC', 'Turks and Caicos Islands'),
  ('乍得', 'Code taken from name in French: Tchad', now(), 'TD', 'Chad'),
  ('法属南部领地', '\"Covers the French Southern and Antarctic Lands except Adélie Land. \nCode taken from name in French: Terres australes françaises\"', now(), 'TF', 'French Southern Territories'),
  ('多哥', NULL, now(), 'TG', 'Togo'),
  ('泰国', NULL, now(), 'TH', 'Thailand'),
  ('塔吉克斯坦', NULL, now(), 'TJ', 'Tajikistan'),
  ('托克劳', NULL, now(), 'TK', 'Tokelau'),
  ('东帝汶', NULL, now(), 'TP', 'Andorra'),
  ('土库曼斯坦', NULL, now(), 'TM', 'Turkmenistan'),
  ('突尼斯', NULL, now(), 'TN', 'Tunisia'),
  ('汤加', NULL, now(), 'TO', 'Tonga'),
  ('土耳其', NULL, now(), 'TR', 'Turkey'),
  ('特立尼达', NULL, now(), 'TT', 'Trinidad and Tobago'),
  ('图瓦卢', NULL, now(), 'TV', 'Tuvalu'),
  ('中国台湾', '\"Covers the current jurisdiction of the Republic of China except Kinmen and Lienchiang. \nISO country name follows UN designation (due to political status of Taiwan within the UN)\"', now(), 'TW', 'Taiwan, Province of China'),
  ('坦桑尼亚', 'ISO country name follows UN designation (common name: Tanzania)', now(), 'TZ', 'Tanzania, United Republic of'),
  ('乌克兰', '\"Previous ISO country name: Ukrainian SSR. \nCode assigned as the country was already a UN member since 1945\"', now(), 'UA', 'Ukraine'),
  ('乌干达', NULL, now(), 'UG', 'Uganda'),
  ('美国本土外小岛屿', 'Consists of nine minor insular areas of the United States: Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Islands, Navassa Island, Palmyra Atoll, and Wake Island', now(), 'UM', 'United States Minor Outlying Islands'),
  ('美国', NULL, now(), 'US', 'United States of America'),
  ('乌拉圭', NULL, now(), 'UY', 'Uruguay'),
  ('乌兹别克斯坦', NULL, now(), 'UZ', 'Uzbekistan'),
  ('梵蒂冈', '\"Covers Vatican City, territory of the Holy See. \nPrevious ISO country name: Vatican City State (Holy See)\"', now(), 'VA', 'Holy See'),
  ('圣文森特和格林纳丁斯', NULL, now(), 'VC', 'Saint Vincent and the Grenadines'),
  ('委内瑞拉', 'ISO country name follows UN designation (common name and previous ISO country name: Venezuela)', now(), 'VE', 'Venezuela, Bolivarian Republic of'),
  ('英属维尔京群岛', NULL, now(), 'VG', 'Virgin Islands, British'),
  ('美属维京群岛', NULL, now(), 'VI', 'Virgin Islands, U.S.'),
  ('越南', 'ISO country name follows UN designation (common name: Vietnam)', now(), 'VN', 'Viet Nam'),
  ('瓦努阿图', 'Name changed from New Hebrides (NH)', now(), 'VU', 'Vanuatu'),
  ('瓦利斯和富图纳', NULL, now(), 'WF', 'Wallis and Futuna'),
  ('萨摩亚', 'Code taken from former name: Western Samoa', now(), 'WS', 'Samoa'),
  ('也门', '\"Previous ISO country name: Yemen, Republic of. \nCode used for North Yemen before 1990\"', now(), 'YE',
   'Yemen'),
  ('马约特', NULL, now(), 'YT', 'Mayotte'),
  ('南非', 'Code taken from name in Dutch: Zuid-Afrika', now(), 'ZA', 'South Africa'),
  ('赞比亚', NULL, now(), 'ZM', 'Zambia'),
  ('津巴布韦', 'Name changed from Southern Rhodesia (RH)', now(), 'ZW', 'Zimbabwe');
