SET foreign_key_checks = 0;
TRUNCATE `country`;
TRUNCATE `customer`;
TRUNCATE `disease_type`;
TRUNCATE `group`;
TRUNCATE `user`;
TRUNCATE `user_logon`;
TRUNCATE `user_role`;
TRUNCATE `website`;
SET foreign_key_checks = 1;
